name: test-environment
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - distributed
  - toolz
  - Cython
  - sphinx
  - matplotlib
  - scipy
  - pyyaml
  - coveralls
  - coverage
  - codecov
  - behave
  - netcdf4
  - h5py
  - mock
  - pytest
  - pytest-cov
  - responses
  - platformdirs
  - python-geotiepoints
  - pip
  - pip:
    - trollsift
